name: mvvm_flutter_template
description: >
  قالب پروژه فلاتر بر اساس معماری MVVM با استفاده از Riverpod و Freezed.
  این قالب شامل پوشه‌بندی مدرن، کدهای تکراری و مثال‌های کاربردی برای هر لایه از پروژه می‌باشد.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1 